language: node_js
node_js:
    - "0.10"
before_install:
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - npm install -g grunt-cli
install: npm install
before_script: grunt build
