language: node_js
node_js:
- '8'
services:
- docker
before_install:
- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- docker --version
- docker-compose --version
install:
- cd pac-generator-devops
- npm install -g grunt-cli && npm install
- docker-compose -f docker-compose.production.yml up --build -d
- docker cp pac-generator-client:/usr/src/app/dist ./assets
after_success:
- if [ "$TRAVIS_BRANCH" = "master" ]; then docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
  grunt predeploy --SHA1=$TRAVIS_COMMIT; fi;
deploy:
  edge: true
  skip_cleanup: true
  zip-file: predeploy/pac-generator-$TRAVIS_COMMIT.zip
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: us-east-1
  app: pac-generator
  env: pac-generator-dev-02
  bucket_name: elasticbeanstalk-us-east-1-798511191442
  on:
    repo: davidsmith2/pac-generator
    branch: master
env:
  global:
  - secure: OF7c/I5Olm5GmBQJdhDnfJGXwFBafiwb9+iAq6bqfqgW/KGYbRNYt+WoqkysUIYe8/sV6EzMejSHrfHaSFLyMbl2xWwMJdVmJhi/UCDoUwmcFOzpjpUSjSTJBrTCC2aETrXudtgbddWIB43pgm2dSjO5r7VJU0zbK0zKlvOhCB4=
  - secure: HAdMcPgvyeCPD5xy9SM4FcYnmwpbBYoaaay3eOfilXw5v4Tc+ZgZ1Sf10y0h9CM/Lxym90dEKN/D6vPSiI9hIlHvJq7EBPFYFY59G+w66G4BDOm1p1mb52S/qhB3oyPrHk6Xs9wgzapbovisYUpsWEgORY1D9q8gcuTgYgfxRec=
  - secure: OZ8UN7wohui6JV4kQ4fpLI7+Zq6ZN9MGvNzy7OmAn9/onAOmQ27P773ZFkqiqSRb1njzbADXVolaLXPCEh5G95cD47DeOFp8YZpiojyOQ0xYX55yl8mp8jD/lYgzTJzxemptCe0lSHty0dhfaDeQnpr+mh+xIWCOlW0Vjk7rQWo=
  - secure: bm63fOU8lmbMxtF+tzmEF3xSGkTsPGFH3KP92XTA+uhAebdyriL2fB/HcQsYGl1DcHPuClkrM64yjjEUCEEwOORNdpa3MPCc062zKd7EYUgOJ39wBRCSmpN7jDGN+hakDETv8f3n/AKRmZfTmjWu4DVUcCkuwDMTy/KvJWMVvEs=
