version: '2'

services:

  node-onbuild:
    container_name: pac-generator-server-onbuild
    image: davidsmith2/pac-generator-server-onbuild
    build:
      context: ./pac-generator-server
      dockerfile: Dockerfile-onbuild

  node:
    container_name: pac-generator-server
    image: davidsmith2/pac-generator-server
    ports:
      - 8081:8081

  grunt-onbuild:
    container_name: pac-generator-client-onbuild
    image: davidsmith2/pac-generator-client-onbuild
    build:
      context: ./pac-generator-client
      dockerfile: Dockerfile-onbuild

  grunt:
    container_name: pac-generator-client
    image: davidsmith2/pac-generator-client

  nginx:
    container_name: pac-generator-proxy
    image: davidsmith2/pac-generator-proxy
    ports:
      - 80:80
