version: '2'

services:

  node:
    container_name: pac-generator-server
    ports:
      - 8081:8081

  grunt:
    container_name: pac-generator-client

  nginx:
    container_name: pac-generator-proxy
    build:
      context: ./pac-generator-proxy
    ports:
      - 80:80

  python-base:
    container_name: pac-generator-pacparser-onbuild

  python:
    container_name: pac-generator-pacparser