version: '2'

services:

  node:
    extends:
      file: common-services.yml
      service: node
    build:
      context: ./pac-generator-server
      dockerfile: Dockerfile-production

  grunt:
    extends:
      file: common-services.yml
      service: grunt
    build:
      context: ./pac-generator-client
      dockerfile: Dockerfile-production
    volumes:
      - assets:/home

  nginx:
    extends:
      file: common-services.yml
      service: nginx
    build:
      context: ./pac-generator-proxy
      dockerfile: Dockerfile
    links:
      - node:pac-generator-server
      - grunt:pac-generator-client
    volumes:
      - assets:/home

volumes:
  assets: {}