FROM node:0.10

ENV HOME=/home/app

COPY package.json $HOME/pac-generator/

WORKDIR $HOME/pac-generator

ONBUILD RUN npm install -g grunt-cli && npm install

ONBUILD COPY Gruntfile.js $HOME/pac-generator/

ONBUILD COPY tasks $HOME/pac-generator/tasks
