FROM nginx

RUN apt-get update && apt-get install -y curl

RUN curl -sL https://deb.nodesource.com/setup_0.10 | bash -

RUN apt-get update && apt-get install -y nodejs

ENV HOME=/home/app

COPY package.json $HOME/pac-generator/

WORKDIR $HOME/pac-generator

RUN npm install -g grunt-cli && npm install

COPY nginx.conf /etc/nginx/nginx.conf

COPY Gruntfile.js $HOME/pac-generator/

COPY tasks $HOME/pac-generator/tasks

RUN grunt build

EXPOSE 80

CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
