forge "https://forgeapi.puppetlabs.com"
mod "puppetlabs/apache"
mod "apt",
    :git => "git://github.com/puppetlabs/puppetlabs-apt.git"
mod "baseconfig",
    :path => "./modules/baseconfig"
mod "concat",
    :git => "git://github.com/puppetlabs/puppetlabs-concat.git"
mod "nodejs",
    :git => "git://github.com/puppetlabs/puppetlabs-nodejs.git"
mod "stdlib",
    :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"
